// AUTO-GENERATED by NativeFlow auth-codegen. Do not edit by hand.

export type AuthStatus = 'idle' | 'authenticated' | 'unauthenticated' | 'expired';

export interface NormalizedUser {
  id: string;
  email: string | null;
  displayName: string | null;
}

export interface AuthState {
  status: AuthStatus;
  user: NormalizedUser | null;
  permissions: string[];
}

export type LoginInput =
  | { kind: 'password'; email: string; password: string }
  | { kind: 'oauth'; provider: string }
  | { kind: 'sso' };

export interface AuthProvider {
  login(input: LoginInput): Promise<AuthState>;
  logout(): Promise<void>;
  getToken(): Promise<string | null>;
  refreshToken(): Promise<string | null>;
  getCurrentUser(): Promise<NormalizedUser | null>;
  getPermissions(): Promise<string[]>;
  onAuthStateChange(cb: (state: AuthState) => void): () => void;
}
